---
- name: Install Apache Tomcat10 
  hosts: webserver
  become: true
  tasks:      
    - name: Update the System Packages
      apt:
        update_cache: yes
    
    - name: Install JAVA
      apt:
        name: default-jdk
        state: present
 
    - name: Create a Tomcat User
      user:
        name: tomcat
 
    - name: Create a Tomcat Group
      group:
        name: tomcat
 
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: download & unarchive tomcat10 
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]
 
    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
 
    - name: Copy Tomcat service from local to remote
      copy:
        src: ./etc/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755
 
    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
    
    - name: create tomcat-user.xml file
      copy:
        src: tomcat-users.xml
        dest: /opt/tomcat/conf/

    - name: create context.xml in manager file
      copy:
        src: manager/context.xmlmanager
        dest: /opt/tomcat/webapps//META-INF/

    - name: create context.xml in host-manager file
      copy:
        src: hostmanager/context.xml
        dest: /opt/tomcat/webapps/host-manager/META-INF/

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted

    