- name: Deploy Docker image
  hosts: '{{ deploy_server }}'
  become: yes
  tasks:
    - name: Docker stop
      shell: docker rm  -f {{ container_name }}

    - name: Pull docker image {{ job_name }}:{{ build_no }}
      command: docker pull {{ job_name }}:{{ build_no }}

    - name: run docker image {{ job_name }}:{{ build_no }}
      command: docker run --name {{ container_name }} -d -p {{ port_no }}:8080 {{ job_name }}:{{ build_no }}
