---
# tasks file for tomcat
- name: Create a Tomcat User
  user:
    name: tomcat
 
- name: Create a Tomcat Group
  group:
    name: tomcat

- name: Create a Tomcat Directory
  file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes
 
- name: download & unarchive tomcat10 
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz
    dest: /opt/tomcat10
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Change ownership of tomcat directory
  file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Copy Tomcat service from local to remote
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/
    mode: 0755

- name: Start and Enable Tomcat 10 on sever
  systemd:
    name: tomcat
    state: started
    daemon_reload: true

- name: create tomcat-user.xml file
  copy:
    src: tomcat-users.xml
    dest: /opt/tomcat10/conf/

- name: create context.xml in manager file
  copy:
    src: manager-context.xml
    dest: /opt/tomcat10/webapps/manager/META-INF/context.xml

- name: create context.xml in host-manager file
  copy:
    src: host-manager-context.xml
    dest: /opt/tomcat10/webapps/host-manager/META-INF/context.xml

- name: Restart Tomcat
  service:
    name: tomcat
    state: restarted

- name: check tomcat respose
  wait_for: port=8080 timeout=10
